// Sync the shared game files from ../web into this Next app (server lib + browser /public/game),
// and regenerate lib/gameHtml.js. Run after editing the static game or re-running the data pipeline.
//   npm run sync
import { copyFileSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { createHash } from "node:crypto";

const root = process.cwd();                 // web-next/
const web = resolve(root, "..", "web");

const copies = [
  ["players.js", ["lib/players.js", "public/game/players.js"]],
  ["engine.js",  ["lib/engine.js",  "public/game/engine.js"]],
  ["app.js",     ["public/game/app.js"]],
  ["styles.css", ["public/game/styles.css", "app/game.css"]],
];

for (const [src, dests] of copies) {
  const from = resolve(web, src);
  for (const d of dests) {
    const out = resolve(root, d);
    mkdirSync(dirname(out), { recursive: true });
    copyFileSync(from, out);
    console.log("✓", src, "→", d);
  }
}

// Content-hash version for the /game/* assets. app/page.js appends it as ?v=… so the assets can be
// served with an immutable Cache-Control (see next.config.mjs) yet bust on every sync.
const v = createHash("sha256")
  .update(readFileSync(resolve(web, "players.js")))
  .update(readFileSync(resolve(web, "engine.js")))
  .update(readFileSync(resolve(web, "app.js")))
  .digest("hex")
  .slice(0, 8);
writeFileSync(
  resolve(root, "lib/gameAssets.js"),
  "// AUTO-GENERATED by `npm run sync` — do not edit by hand.\n" +
    `export const GAME_V = "${v}";\n`
);
console.log("✓ game asset version:", v);

// Regenerate the game markup injected by app/page.js (everything in <body> before the <script> tags).
const html = readFileSync(resolve(web, "index.html"), "utf8");
const body = html.slice(html.indexOf("<body>") + 6, html.indexOf("<script")).trim();
writeFileSync(
  resolve(root, "lib/gameHtml.js"),
  "// AUTO-GENERATED by `npm run sync` from ../web/index.html — do not edit by hand.\n" +
    "export const GAME_BODY = " + JSON.stringify(body) + ";\n"
);
console.log("✓ regenerated lib/gameHtml.js");
console.log("Done. Game files are in sync.");
